// app/(payments)/layout.tsx
import React from "react";
import "../globals.css";
import { CartProvider } from "@/providers/cart-provider";
import { Toaster } from "sonner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "T-finity",
  description: "Generated by create next app",
};

interface PaymentsLayoutProps {
  children: React.ReactNode;
}

export default function PaymentsLayout({ children }: PaymentsLayoutProps) {
  return <CartProvider>{children}</CartProvider>;
}
