import "../globals.css";
import { CartProvider } from "@/providers/cart-provider";
import { WishlistProvider } from "@/providers/wishlist-provider";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { CartSidebar } from "@/components/cart-sidebar";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "T-finity",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WishlistProvider>
      <CartProvider>
        <Navbar />
        <main>{children}</main>
        <Footer />
        <Toaster
          position="top-center"
          duration={3000}
          theme="dark"
          richColors
          closeButton
        />
      </CartProvider>
    </WishlistProvider>
  );
}
