import "../globals.css";
import { CartProvider } from "@/providers/cart-provider";
import { WishlistProvider } from "@/providers/wishlist-provider";
import Navbar from "../components/Navbar";
import Nav2 from "../components/Nav2";
import { PromoCodeBanner } from "../components/PromoCodeBanner";
import Footer from "../components/Footer";
import { CartSidebar } from "@/components/cart-sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "T-finity",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WishlistProvider>
      <CartProvider>
        <Navbar />
        <Nav2 />
        <PromoCodeBanner />
        <main>{children}</main>
        <Footer />
        <CartSidebar />
      </CartProvider>
    </WishlistProvider>
  );
}
