// app/(auth)/layout.tsx
import React from "react";
import "../globals.css";
import { CartProvider } from "@/providers/cart-provider";
import { Toaster } from "sonner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "T-finity",
  description: "Generated by create next app",
};

interface AuthLayoutProps {
  children: React.ReactNode;
}

export default function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <CartProvider>
      {children}
      <Toaster
        position="top-center"
        duration={5000}
        theme="dark"
        richColors
        closeButton
      />
    </CartProvider>
  );
}
