import "../globals.css";
import { CartProvider } from "@/providers/cart-provider";
import { WishlistProvider } from "@/providers/wishlist-provider";
import { CartSidebar } from "@/components/cart-sidebar";
import { Metadata } from "next";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import { ShopLayoutClient } from "./layout-client";

export const metadata: Metadata = {
  title: "T-finity",
  description: "Generated by create next app",
};

export default async function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WishlistProvider>
      <CartProvider>
        <ShopLayoutClient />
        <Navbar />
        <main>{children}</main>
        <Footer />
        <CartSidebar />
      </CartProvider>
    </WishlistProvider>
  );
}
